import requests
import sys
import datetime as dt

mod_id = 5890
game_id = 2673
type_id = 1
category_id = 7
mod_version = "1.0.0"
mod_author = "SwordFisherL42"
mod_name = "Demonic Eyes - Glowing Red Eyes Reshade (U11)"
summary_data = f"""Autogenerated {dt.datetime.now().strftime("%m/%d/%Y, %H:%M:%S")}"""
desc_data = f"""
[i]{dt.datetime.now().strftime("%m/%d/%Y, %H:%M:%S")} - THIS POST WAS AUTOGENERATED[/i] 🤖
"""

headers ={
    'user-agent': r'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36',
    'cookie': sys.argv[1]
}
data = {"id": mod_id, 
"game_id": game_id, 
"new_game_name": "", 
"type": type_id, 
"category_id": category_id, 
"suggested_category_id": None, 
"suggested_new_category": "", 
"name": mod_name, 
"language_id": 0, 
"version": mod_version,
"author": mod_author, 
"summary": summary_data,
"description": desc_data ,
"tag_gore": 0, 
"tag_nudity": 0, 
"tag_skimpy": 0, 
"tag_sexualised": 0, 
"tag_profanity": 0, 
"classtags": ""}
r = requests.post("https://www.nexusmods.com/Core/Libs/Common/Managers/Mods?Save", data=data, headers=headers)
jdata = r.json()
print(f"Response content: {r.content}\nCode: {r.status_code}")
print(f"Status {jdata['status']}")